{
  "exception_throw": [
    {
      "evaluation item": "完整度->链路跟踪完整度->异常与错误处理->异常抛出->exception_try",
      "compose": "exception_try_001_T.js && !exception_try_002_F.js",
      "level": "3"
    },
    {
      "evaluation item": "完整度->链路跟踪完整度->异常与错误处理->异常抛出->exception_catch",
      "compose": "exception_catch_001_T.js && !exception_catch_002_F.js",
      "level": "3"
    },
    {
      "evaluation item": "完整度->链路跟踪完整度->异常与错误处理->异常抛出->exception_catch",
      "compose": "exception_catch_003_T.js && !exception_catch_004_F.js",
      "level": "3"
    },
    {
      "evaluation item": "完整度->链路跟踪完整度->异常与错误处理->异常抛出->exception_finally",
      "compose": "exception_finally_001_T.js && !exception_finally_002_F.js",
      "level": "3"
    }
  ]
}